.github/workflows/maven-ci.yml
maven-settings.xml
pom.xml

Fix: https://github.com/casdoor/casdoor-java-sdk/issues/9
Signed-off-by: “seriouszyx” <674965440@qq.com>

feat: add semantic-release

---

.github/workflows/maven-ci.yml
README.md
pom.xml

Signed-off-by: “seriouszyx” <seriouszyx@foxmail.com>
Fix: https://github.com/casdoor/casdoor-java-sdk/issues/8

docs: add badges

---

src/main/java/org/casbin/casdoor/entity/CasdoorSmsForm.java
src/main/java/org/casbin/casdoor/service/CasdoorSmsService.java

For sync with Casdoor server-side: https://github.com/casbin/casdoor/pull/310

feat: add organizationId to CasdoorSmsForm

---

src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java

Fix: https://github.com/casdoor/casdoor-java-sdk/issues/14
Signed-off-by: “seriouszyx” <seriouszyx@foxmail.com>

feat: add methods to get URLs

---

src/main/java/org/casbin/casdoor/service/CasdoorUserService.java
src/main/test/java/org/casbin/casdoor/CasdoorUserServiceTest.java

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

feat: add getSortedUsers(), getUserCount() and getUserByEmail() APIs

---

.gitignore
src/main/java/org/casbin/casdoor/config/CasdoorConfig.java
src/main/java/org/casbin/casdoor/exception/CasdoorException.java
src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java
src/main/test/java/org/casbin/casdoor/CasdoorAuthServiceTest.java

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

feat: use RS256 to sign JWT token

---

README.md
src/main/java/org/casbin/casdoor/exception/CasdoorAuthException.java
src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java
src/main/java/org/casbin/casdoor/service/CasdoorEmailService.java
src/main/java/org/casbin/casdoor/service/CasdoorUserService.java
src/main/java/org/casbin/casdoor/util/http/HttpClient.java

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

fix: improve custom exception handling and update docs

---

pom.xml

Refer to: https://github.com/jenkins-infra/repository-permissions-updater/issues/2379#issuecomment-1054046999

fix: vulnerable dependencies

---

README.md
src/main/java/org/casbin/casdoor/config/CasdoorConfig.java
src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java

Fix: https://github.com/casdoor/casdoor-java-sdk/issues/26

fix: update the parameter from jwtPublicKey to certificate

---

src/main/java/org/casbin/casdoor/entity/CasdoorPermission.java
src/main/java/org/casbin/casdoor/entity/CasdoorRole.java
src/main/java/org/casbin/casdoor/entity/CasdoorUser.java

feat: add roles and permissions for user

---

src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java
src/main/java/org/casbin/casdoor/util/QueryUtils.java

feat: support profile returnUrl 
https://github.com/casdoor/casdoor/pull/1152

feat: support profile returnUrl

---

pom.xml
src/main/java/org/casbin/casdoor/config/CasdoorConfig.java
src/main/java/org/casbin/casdoor/entity/CasdoorEmailForm.java
src/main/java/org/casbin/casdoor/entity/CasdoorPermission.java
src/main/java/org/casbin/casdoor/entity/CasdoorResource.java
src/main/java/org/casbin/casdoor/entity/CasdoorRole.java
src/main/java/org/casbin/casdoor/entity/CasdoorSmsForm.java
src/main/java/org/casbin/casdoor/entity/CasdoorUser.java
src/main/java/org/casbin/casdoor/entity/Organization.java
src/main/java/org/casbin/casdoor/util/http/CasdoorResponse.java

feat: remove lombok

---

src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java

https://github.com/jenkins-infra/repository-permissions-updater/issues/2379

feat: support user specified state

---

.github/workflows/maven-ci.yml
src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java

Fix: https://github.com/casdoor/casdoor-java-sdk/issues/40

fix: fix getUserProfileUrl format.

---

src/main/java/org/casbin/casdoor/entity/CasdoorToken.java
src/main/java/org/casbin/casdoor/service/CasdoorEnforcerService.java
src/main/java/org/casbin/casdoor/service/CasdoorPermissionService.java
src/main/java/org/casbin/casdoor/service/CasdoorRoleService.java
src/main/java/org/casbin/casdoor/service/CasdoorTokenService.java
src/main/java/org/casbin/casdoor/service/CasdoorUserService.java
src/main/java/org/casbin/casdoor/util/MapToUrlUtils.java
src/main/java/org/casbin/casdoor/util/PermissionOperations.java
src/main/java/org/casbin/casdoor/util/RoleOperations.java
src/main/java/org/casbin/casdoor/util/http/CasdoorResponse.java
src/main/java/org/casbin/casdoor/util/http/HttpClient.java
src/main/test/java/org/casbin/casdoor/CasdoorEnforcerServiceTest.java
src/main/test/java/org/casbin/casdoor/CasdoorPermissionServiceTest.java
src/main/test/java/org/casbin/casdoor/CasdoorRoleServiceTest.java
src/main/test/java/org/casbin/casdoor/CasdoorTokenServiceTest.java

Fix: https://github.com/casdoor/casdoor-java-sdk/issues/43

feat: add APIs like role, enforcer, token and permission

---

src/main/java/org/casbin/casdoor/entity/CasdoorPermission.java

- description
- domains
- submitter
- approver
- approveTime
- state

feat: add new introduced properties of permissions

---

src/main/java/org/casbin/casdoor/entity/CasdoorOrganization.java

refactor!: Rename entity Organization

---

src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java

For: https://github.com/casdoor/casdoor-spring-boot-starter/issues/36

fix: fix JWT parse bug

---

src/main/java/org/casbin/casdoor/service/CasdoorTokenService.java
src/test/java/org/casbin/casdoor/CasdoorTokenServiceTest.java

Fix: https://github.com/casdoor/casdoor-java-sdk/issues/57

fix: fix query token bug

---

src/main/java/org/casbin/casdoor/entity/CasbinRule.java
src/main/java/org/casbin/casdoor/service/EnforcerService.java
src/main/java/org/casbin/casdoor/service/PolicyService.java
src/main/java/org/casbin/casdoor/util/EnforcerOperations.java
src/main/java/org/casbin/casdoor/util/PolicyOperations.java
src/test/java/org/casbin/casdoor/EnforcerTest.java
src/test/java/org/casbin/casdoor/PolicyTest.java

Fix: https://github.com/casdoor/casdoor/issues/2787

feat: add policy APIs

---

src/main/java/org/casbin/casdoor/service/AuthService.java
src/main/java/org/casbin/casdoor/service/GroupService.java

Fix: https://github.com/casdoor/casdoor-java-sdk/issues/76

feat: add getGroups(Boolean withTree) API

---

src/main/java/org/casbin/casdoor/entity/Group.java

feat: fix Group.Users should be string array bug

---

src/main/java/org/casbin/casdoor/service/ProductService.java
src/test/java/org/casbin/casdoor/ProductTest.java

Fix: https://github.com/casdoor/casdoor-java-sdk/issues/90

feat: add buyProduct() API
